# Generated by Django 5.1.2 on 2024-10-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderproducts',
            name='price',
            field=models.DecimalField(decimal_places=2, default='100', max_digits=12),
        ),
        migrations.AlterField(
            model_name='cartorderproducts',
            name='total',
            field=models.DecimalField(decimal_places=2, default='200', max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default='200', max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='100', max_digits=12),
        ),
    ]
